import React, { Component } from 'react';
import { ICategory } from '../interfaces/category.interface';
import { IProduct } from '../interfaces/product.interface';
import 'react-toastify/dist/ReactToastify.css';
import { ICustomer } from '../interfaces/customer.interface';
interface ICartItem extends IProduct {
    cartId: string;
    quantity: number | undefined;
    old_quantity: number;
}
type Props = {
    order: string;
    settings: any;
};
type State = {
    orderId: string;
    orderNumber: string;
    categories: ICategory[];
    products: IProduct[];
    customers: ICustomer[];
    customer: ICustomer | undefined;
    customerName: string | null;
    customerEmail: string | null;
    customerMobile: string | null;
    customerCity: string | null;
    customerBuilding: string | null;
    customerStreet: string | null;
    customerFloor: string | null;
    customerApartment: string | null;
    cart: ICartItem[];
    deletedProducts: ICartItem[];
    showProducts: boolean;
    categoryName: string | null;
    total: number;
    subtotal: number;
    tax: number | undefined;
    vatType: string;
    deliveryCharge: number | undefined;
    discount: number | undefined;
    tenderAmount: number | undefined;
    searchValue: string | null;
    remarks: string | null;
    isFullScreen: boolean;
    isLoading: boolean;
    isLoadingCategories: boolean;
    currentPrice: number;
};
declare class PointOfSaleEdit extends Component<Props, State> {
    constructor(props: Props);
    getAppSettings: () => any;
    componentDidMount(): void;
    setupForEditing: () => Promise<void>;
    randomString: () => string;
    getCategories: () => void;
    updateOrder: () => void;
    categoryClick: (category: ICategory) => void;
    backClick: () => void;
    toggleFullScreen: () => void;
    goToOrderList: () => void;
    calculateTotal: () => void;
    getVat: () => number;
    getTaxAmount: () => number;
    getTotalTax: () => number;
    handleDiscountChange: (event: React.ChangeEvent<HTMLInputElement>) => void;
    handleTaxChange: (event: React.ChangeEvent<HTMLInputElement>) => void;
    handleDeliveryChargeChange: (event: React.ChangeEvent<HTMLInputElement>) => void;
    updateItemQuantity: (event: React.ChangeEvent<HTMLInputElement>, item: ICartItem) => void;
    updateItemPrice: (event: React.ChangeEvent<HTMLInputElement>, item: ICartItem) => void;
    currencyFormatValue: (number: any) => any;
    getChangeAmount: () => number;
    handleTenderAmountChange: (event: React.ChangeEvent<HTMLInputElement>) => void;
    handleRemarksChange: (event: React.FormEvent<HTMLTextAreaElement>) => void;
    removeItem: (item: ICartItem) => void;
    addToCart: (product: IProduct) => void;
    handleSearchChange: (event: React.FormEvent<HTMLInputElement>) => void;
    handleCustomerSearchChange: (event: React.FormEvent<HTMLInputElement>) => void;
    setCustomer: (customer: ICustomer) => void;
    selectCustomer(customer: ICustomer): void;
    closeModal: (id: string) => void;
    removeCustomer(): void;
    createCustomer: (e: React.FormEvent<HTMLFormElement>) => void;
    handleVatTypeChange: (event: any) => void;
    handleCustomerNameChange: (event: React.FormEvent<HTMLInputElement>) => void;
    handleCustomerEmailChange: (event: React.FormEvent<HTMLInputElement>) => void;
    handleCustomerMobileChange: (event: React.FormEvent<HTMLInputElement>) => void;
    handleCustomerCityChange: (event: React.FormEvent<HTMLInputElement>) => void;
    handleCustomerStreetChange: (event: React.FormEvent<HTMLInputElement>) => void;
    handleCustomerBuildingChange: (event: React.FormEvent<HTMLInputElement>) => void;
    handleCustomerFloorChange: (event: React.FormEvent<HTMLInputElement>) => void;
    handleCustomerApartmentChange: (event: React.FormEvent<HTMLInputElement>) => void;
    modalCloseButton: () => React.ReactNode;
    pricesFilter: () => React.ReactNode;
    handleSelectRadio: (index: number) => void;
    pricesFilterModal: () => React.ReactNode;
    render(): JSX.Element;
}
export default PointOfSaleEdit;
